---
title: "Assignment 4"
description: | 
  The N400 effect
date: 05-28-2021
author:
  - first_name: "Andrew"
    last_name: "Ellis"
    url: https://github.com/awellis
    affiliation: Kognitive Psychologie, Wahrnehmung und Methodenlehre, Universität Bern 
    affiliation_url: https://www.kog.psy.unibe.ch
    orcid_id: 0000-0002-2788-936X

citation_url: https://awellis.github.io/learnmultilevelmodels/asssignment-4.html
bibliography: ./bibliography.bib
output: 
    distill::distill_article:
      toc: true
      toc_float: true
      toc_depth: 2
      code_folding: false
      self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


```{r}
library(tidyverse)
library(brms)

theme_set(theme_grey(base_size = 14) +
            theme(panel.grid = element_blank()))
```


This [example](https://vasishth.github.io/bayescogsci/book/sec-N400hierarchical.html#sec:mcvivs) is borrowed the companion website for the @shravanvasishthIntroductionBayesianData.

```{r eval=FALSE, include=TRUE}
# install.packages("remotes")
remotes::install_github("bnicenboim/bcogsci")
```


```{r}
library(bcogsci)
data(df_eeg)

df_eeg <- df_eeg %>%
  mutate(c_cloze = cloze - mean(cloze))
```



```{r}
df_eeg
```


:::exercise

:::



```{r eval=FALSE, include=FALSE}
lm1 <- lme4::lmer(n400 ~ cloze + (1 | subj), data = df_eeg)
```












































































































































































```{r}
fit_N400_v <- brm(n400 ~ c_cloze + (c_cloze || subj),
                  prior =
                      c(prior(normal(0, 10), class = Intercept),
                        prior(normal(0, 10), class = b, coef = c_cloze),
                        prior(normal(0, 50), class = sigma),
                        prior(normal(0, 20), class = sd, coef = Intercept, group = subj),
                        prior(normal(0, 20), class = sd, coef = c_cloze, group = subj)
                        ),
              data = df_eeg)
```

